### ISSUE TITLE
purs fails to run on Cygwin

### ISSUE THREAD

**Issue by cebaa** [purescript-contrib/node-purescript#54]
Installing a fresh purescript:

```
$ npm install -g purescript
```

(current version `purescript@0.11.7`) leaves the following `purs` script:

```
"$basedir/node_modules/purescript/purs.bin"   "$@"
exit $?
```

When run:

```
$ purs
/cygdrive/c/node-6.11.1/purs: line 1: /node_modules/purescript/purs.bin: No such file or directory
```

Changing to something like this (similar to e.g. `pulp` script) seems to solve the issue:

```
#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

"$basedir/node_modules/purescript/purs.bin" "$@"
exit $?
```

**Comment by shinnn** [comment]
### The cause

1. `purs` script is generated by [npm CLI](https://github.com/npm/npm/) while runnning `npm install [--global] purescript`.
2. npm CLI [uses](https://github.com/npm/npm/blob/0cc9d89ed2d46745f91d746fda9d205fd39d3daa/lib/build.js#L102) [bin-links](https://github.com/npm/bin-links) to generate binary shims.
3. bin-links [invokes](https://github.com/npm/bin-links/blob/853497c58541da3300ed7025e5905d8f8464466d/index.js#L147) [cmd-shim](https://github.com/npm/cmd-shim) on Windows.
4. cmd-shim does not include the Cygwin-specific `$basedir` modification (`case uname in *CYGWIN* ...`) to the generated script [if the source has no shebang](https://github.com/npm/cmd-shim/blob/75edc98dec188cca8b819865699a2eaa5e41afae/index.js#L151).
5. `purs.bin` has no shebang, because it's not a script file but a binary file.

### The solution

Contribute to [cmd-shim](https://github.com/npm/cmd-shim) to make it work for Cygwin even if the source doesn't contain any shebang.
