### ISSUE TITLE
Needs 0.12.0-rc1 pre-release on npm

### ISSUE THREAD

**Issue by justinwoo** [purescript-contrib/node-purescript#56]
This would help be able to conveniently install for CI

**Comment by justinwoo** [comment]
@shinnn could you do this? Or is this doable by other purescript-contrib authors?

**Comment by justinwoo** [comment]
Looks like this can't be done with the current version number parsers. 0.12 proper should be released instead.

**Comment by shinnn** [comment]
Fixed in https://github.com/purescript-contrib/node-purescript/commit/cb1739e1e6b869461af5a2d0d2ef232b01e72659, and now available on npm.

Since the underlying libraries use modern ECMAScript features, for example async functions and object spread properties, this project no longer supports Node.js <= 8.

Therefore, the description in the PureScript website is now stale.

> (Installation via `npm` requires Node version 6 or later)

If anyone is interested, submit a patch to the website repository.
