### ISSUE TITLE
Consider not recompressing binaries after download

### ISSUE THREAD

**Issue by hdgarrood** [purescript-contrib/node-purescript#68]
The compiler binaries are provided as .tar.gz bundles, which are already compressed. However, on sufficiently recent versions of node.js, this package downloads them, checks they work, and then recompresses them, which can take quite a while (up to one minute). This doesn't give the best UX; for the sake of an 4MB hard disk saving over caching the file as downloaded, I'd suggest that it's not worth making the user wait for this long.

**Comment by shinnn** [comment]
Instead, reduce the binary size of PureScript itself. That would give the best UX. About 40 MB, in fact 55 MB on Windows, is too large for a compiler.

Historically I've implemented lots of UX improvements to this installer to cover up the problems of the compiler itself, but I found that they've discouraged the PureScript maintainers fixing the root cause, unfortunately. I don't want to repeat this kind of tragedy.

**Comment by hdgarrood** [comment]
The `purs` binary is not just a compiler, it also provides a repl, a bundling tool, the documentation generator, and a server for ide plugins. But even if the binary was half the size, recompressing it every time would still presumably take quite a while. I find your stance is pretty bewildering to take in 2019, honestly; my `node_modules` directory on a modestly sized frontend app is 294MB.
